### ISSUE TITLE
Move to JavaScript?

### ISSUE THREAD

**Issue by eventualbuddha** [sergeyt/parse-diff#16]
Here's a JS version [powered by decaffeinate](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=false&code=%23%20parses%20unified%20diff%0A%23%20http%3A%2F%2Fwww.gnu.org%2Fsoftware%2Fdiffutils%2Fmanual%2Fdiffutils.html%23Unified-Format%0Amodule.exports%20%3D%20%28input%29%20-%3E%0A%09return%20%5B%5D%20if%20not%20input%0A%09return%20%5B%5D%20if%20input.match%20%2F%5E%5Cs%2B%24%2F%0A%0A%09lines%20%3D%20input.split%20'%5Cn'%0A%09return%20%5B%5D%20if%20lines.length%20%3D%3D%200%0A%0A%09files%20%3D%20%5B%5D%0A%09file%20%3D%20null%0A%09ln_del%20%3D%200%0A%09ln_add%20%3D%200%0A%09current%20%3D%20null%0A%0A%09start%20%3D%20%28line%29%20-%3E%0A%09%09file%20%3D%0A%09%09%09chunks%3A%20%5B%5D%0A%09%09%09deletions%3A%200%0A%09%09%09additions%3A%200%0A%09%09files.push%20file%0A%0A%09%09if%20not%20file.to%20and%20not%20file.from%0A%09%09%09fileNames%20%3D%20parseFile%20line%0A%0A%09%09%09if%20fileNames%0A%09%09%09%09file.from%20%3D%20fileNames%5B0%5D%0A%09%09%09%09file.to%20%3D%20fileNames%5B1%5D%0A%0A%09restart%20%3D%20-%3E%0A%09%09start%28%29%20if%20not%20file%20%7C%7C%20file.chunks.length%0A%0A%09new_file%20%3D%20-%3E%0A%09%09restart%28%29%0A%09%09file.new%20%3D%20true%0A%09%09file.from%20%3D%20'%2Fdev%2Fnull'%0A%0A%09deleted_file%20%3D%20-%3E%0A%09%09restart%28%29%0A%09%09file.deleted%20%3D%20true%0A%09%09file.to%20%3D%20'%2Fdev%2Fnull'%0A%0A%09index%20%3D%20%28line%29%20-%3E%0A%09%09restart%28%29%0A%09%09file.index%20%3D%20line.split%28'%20'%29.slice%281%29%0A%0A%09from_file%20%3D%20%28line%29%20-%3E%0A%09%09restart%28%29%0A%09%09file.from%20%3D%20parseFileFallback%20line%0A%0A%09to_file%20%3D%20%28line%29%20-%3E%0A%09%09restart%28%29%0A%09%09file.to%20%3D%20parseFileFallback%20line%0A%0A%09chunk%20%3D%20%28line%2C%20match%29%20-%3E%0A%09%09ln_del%20%3D%20oldStart%20%3D%20%2Bmatch%5B1%5D%0A%09%09oldLines%20%3D%20%2B%28match%5B2%5D%20%7C%7C%200%29%0A%09%09ln_add%20%3D%20newStart%20%3D%20%2Bmatch%5B3%5D%0A%09%09newLines%20%3D%20%2B%28match%5B4%5D%20%7C%7C%200%29%0A%09%09current%20%3D%20%7B%0A%09%09%09content%3A%20line%2C%0A%09%09%09changes%3A%20%5B%5D%2C%0A%09%09%09oldStart%2C%20oldLines%2C%20newStart%2C%20newLines%0A%09%09%7D%0A%09%09file.chunks.push%20current%0A%0A%09del%20%3D%20%28line%29%20-%3E%0A%09%09current.changes.push%20%7Btype%3A'del'%2C%20del%3Atrue%2C%20ln%3Aln_del%2B%2B%2C%20content%3Aline%7D%0A%09%09file.deletions%2B%2B%0A%0A%09add%20%3D%20%28line%29%20-%3E%0A%09%09current.changes.push%20%7Btype%3A'add'%2C%20add%3Atrue%2C%20ln%3Aln_add%2B%2B%2C%20content%3Aline%7D%0A%09%09file.additions%2B%2B%0A%0A%09noeol%20%3D%20'%5C%5C%20No%20newline%20at%20end%20of%20file'%0A%09normal%20%3D%20%28line%29%20-%3E%0A%09%09return%20if%20not%20file%0A%09%09current.changes.push%20%7B%0A%09%09%09type%3A%20'normal'%0A%09%09%09normal%3A%20true%0A%09%09%09ln1%3A%20ln_del%2B%2B%20unless%20line%20is%20noeol%0A%09%09%09ln2%3A%20ln_add%2B%2B%20unless%20line%20is%20noeol%0A%09%09%09content%3A%20line%0A%09%09%7D%0A%0A%09schema%20%3D%20%5B%0A%09%09%23%20todo%20beter%20regexp%20to%20avoid%20detect%20normal%20line%20starting%20with%20diff%0A%09%09%5B%2F%5E%5Cs%2B%2F%2C%20normal%5D%0A%09%09%5B%2F%5Ediff%5Cs%2F%2C%20start%5D%2C%0A%09%09%5B%2F%5Enew%20file%20mode%20%5Cd%2B%24%2F%2C%20new_file%5D%2C%0A%09%09%5B%2F%5Edeleted%20file%20mode%20%5Cd%2B%24%2F%2C%20deleted_file%5D%2C%0A%09%09%5B%2F%5Eindex%5Cs%5B%5Cda-zA-Z%5D%2B%5C.%5C.%5B%5Cda-zA-Z%5D%2B%28%5Cs%28%5Cd%2B%29%29%3F%24%2F%2C%20index%5D%2C%0A%09%09%5B%2F%5E---%5Cs%2F%2C%20from_file%5D%2C%0A%09%09%5B%2F%5E%5C%2B%5C%2B%5C%2B%5Cs%2F%2C%20to_file%5D%2C%0A%09%09%5B%2F%5E%40%40%5Cs%2B%5C-%28%5Cd%2B%29%2C%3F%28%5Cd%2B%29%3F%5Cs%2B%5C%2B%28%5Cd%2B%29%2C%3F%28%5Cd%2B%29%3F%5Cs%40%40%2F%2C%20chunk%5D%2C%0A%09%09%5B%2F%5E-%2F%2C%20del%5D%2C%0A%09%09%5B%2F%5E%5C%2B%2F%2C%20add%5D%0A%09%5D%0A%0A%09parse%20%3D%20%28line%29%20-%3E%0A%09%09for%20p%20in%20schema%0A%09%09%09m%20%3D%20line.match%20p%5B0%5D%0A%09%09%09if%20m%0A%09%09%09%09p%5B1%5D%28line%2C%20m%29%0A%09%09%09%09return%20true%0A%09%09return%20false%0A%0A%09for%20line%20in%20lines%0A%09%09parse%20line%0A%0A%09return%20files%0A%0AparseFile%20%3D%20%28s%29%20-%3E%0A%09return%20if%20not%20s%0A%0A%09fileNames%20%3D%20s.split%28'%20'%29.slice%28-2%29%0A%09fileNames.map%20%28fileName%2C%20i%29%20-%3E%0A%09%09fileNames%5Bi%5D%20%3D%20fileName.replace%28%2F%5E%28a%7Cb%29%5C%2F%2F%2C%20''%29%0A%0A%09return%20fileNames%0A%0A%23%20fallback%20function%20to%20overwrite%20file.from%20and%20file.to%20if%20executed%0AparseFileFallback%20%3D%20%28s%29%20-%3E%0A%09s%20%3D%20ltrim%20s%2C%20'-'%0A%09s%20%3D%20ltrim%20s%2C%20'%2B'%0A%09s%20%3D%20s.trim%28%29%0A%09%23%20ignore%20possible%20time%20stamp%0A%09t%20%3D%20%28%2F%5Ct.*%7C%5Cd%7B4%7D-%5Cd%5Cd-%5Cd%5Cd%5Cs%5Cd%5Cd%3A%5Cd%5Cd%3A%5Cd%5Cd%28.%5Cd%2B%29%3F%5Cs%28%5C%2B%7C-%29%5Cd%5Cd%5Cd%5Cd%2F%29.exec%28s%29%0A%09s%20%3D%20s.substring%280%2C%20t.index%29.trim%28%29%20if%20t%0A%09%23%20ignore%20git%20prefixes%20a%2F%20or%20b%2F%0A%09if%20s.match%20%28%2F%5E%28a%7Cb%29%5C%2F%2F%29%20then%20s.substr%282%29%20else%20s%0A%0Altrim%20%3D%20%28s%2C%20chars%29%20-%3E%0A%09s%20%3D%20makeString%28s%29%0A%09return%20trimLeft.call%28s%29%20if%20!chars%20and%20trimLeft%0A%09chars%20%3D%20defaultToWhiteSpace%28chars%29%0A%09return%20s.replace%28new%20RegExp%28'%5E'%20%2B%20chars%20%2B%20'%2B'%29%2C%20''%29%0A%0AmakeString%20%3D%20%28s%29%20-%3E%20if%20s%20%3D%3D%20null%20then%20''%20else%20s%20%2B%20''%0A%0AtrimLeft%20%3D%20String.prototype.trimLeft%0A%0AdefaultToWhiteSpace%20%3D%20%28chars%29%20-%3E%0A%20%20return%20'%5C%5Cs'%20if%20chars%20%3D%3D%20null%0A%20%20return%20chars.source%20if%20chars.source%0A%20%20return%20'%5B'%20%2B%20escapeRegExp%28chars%29%20%2B%20'%5D'%0A%0AescapeRegExp%20%3D%20%28s%29%20-%3E%0A%09makeString%28s%29.replace%28%2F%28%5B.*%2B%3F%5E%3D!%3A%24%7B%7D%28%29%7C%5B%5C%5D%5C%2F%5C%5C%5D%29%2Fg%2C%20'%5C%5C%241'%29). It would need some manual cleanup.

``` js
// parses unified diff
// http://www.gnu.org/software/diffutils/manual/diffutils.html#Unified-Format
export default function(input) {
    if (!input) { return []; }
    if (input.match(/^\s+$/)) { return []; }

    let lines = input.split('\n');
    if (lines.length === 0) { return []; }

    let files = [];
    let file = null;
    let ln_del = 0;
    let ln_add = 0;
    let current = null;

    let start = function(line) {
        file = {
            chunks: [],
            deletions: 0,
            additions: 0
        };
        files.push(file);

        if (!file.to && !file.from) {
            let fileNames = parseFile(line);

            if (fileNames) {
                file.from = fileNames[0];
                return file.to = fileNames[1];
            }
        }
    };

    let restart = function() {
        if (!file || file.chunks.length) { return start(); }
    };

    let new_file = function() {
        restart();
        file.new = true;
        return file.from = '/dev/null';
    };

    let deleted_file = function() {
        restart();
        file.deleted = true;
        return file.to = '/dev/null';
    };

    let index = function(line) {
        restart();
        return file.index = line.split(' ').slice(1);
    };

    let from_file = function(line) {
        restart();
        return file.from = parseFileFallback(line);
    };

    let to_file = function(line) {
        restart();
        return file.to = parseFileFallback(line);
    };

    let chunk = function(line, match) {
        let oldStart;
        let newStart;
        ln_del = oldStart = +match[1];
        let oldLines = +(match[2] || 0);
        ln_add = newStart = +match[3];
        let newLines = +(match[4] || 0);
        current = {
            content: line,
            changes: [],
            oldStart, oldLines, newStart, newLines
        };
        return file.chunks.push(current);
    };

    let del = function(line) {
        current.changes.push({type:'del', del:true, ln:ln_del++, content:line});
        return file.deletions++;
    };

    let add = function(line) {
        current.changes.push({type:'add', add:true, ln:ln_add++, content:line});
        return file.additions++;
    };

    let noeol = '\\ No newline at end of file';
    let normal = function(line) {
        if (!file) { return; }
        return current.changes.push({
            type: 'normal',
            normal: true,
            ln1: line === noeol ? ln_del++ : undefined,
            ln2: line === noeol ? ln_add++ : undefined,
            content: line
        });
    };

    let schema = [
        // todo beter regexp to avoid detect normal line starting with diff
        [/^\s+/, normal],
        [/^diff\s/, start],
        [/^new file mode \d+$/, new_file],
        [/^deleted file mode \d+$/, deleted_file],
        [/^index\s[\da-zA-Z]+\.\.[\da-zA-Z]+(\s(\d+))?$/, index],
        [/^---\s/, from_file],
        [/^\+\+\+\s/, to_file],
        [/^@@\s+\-(\d+),?(\d+)?\s+\+(\d+),?(\d+)?\s@@/, chunk],
        [/^-/, del],
        [/^\+/, add]
    ];

    let parse = function(line) {
        for (let i = 0; i < schema.length; i++) {
            let p = schema[i];
            let m = line.match(p[0]);
            if (m) {
                p[1](line, m);
                return true;
            }
        }
        return false;
    };

    for (let i = 0; i < lines.length; i++) {
        let line = lines[i];
        parse(line);
    }

    return files;
};

var parseFile = function(s) {
    if (!s) { return; }

    let fileNames = s.split(' ').slice(-2);
    fileNames.map((fileName, i) => fileNames[i] = fileName.replace(/^(a|b)\//, ''));

    return fileNames;
};

// fallback function to overwrite file.from and file.to if executed
var parseFileFallback = function(s) {
    s = ltrim(s, '-');
    s = ltrim(s, '+');
    s = s.trim();
    // ignore possible time stamp
    let t = (/\t.*|\d{4}-\d\d-\d\d\s\d\d:\d\d:\d\d(.\d+)?\s(\+|-)\d\d\d\d/).exec(s);
    if (t) { s = s.substring(0, t.index).trim(); }
    // ignore git prefixes a/ or b/
    if (s.match((/^(a|b)\//))) { return s.substr(2); } else { return s; }
};

var ltrim = function(s, chars) {
    s = makeString(s);
    if (!chars && trimLeft) { return trimLeft.call(s); }
    chars = defaultToWhiteSpace(chars);
    return s.replace(new RegExp(`^${chars}+`), '');
};

var makeString = function(s) { if (s === null) { return ''; } else { return s + ''; } };

var { trimLeft } = String.prototype;

var defaultToWhiteSpace = function(chars) {
  if (chars === null) { return '\\s'; }
  if (chars.source) { return chars.source; }
  return `[${escapeRegExp(chars)}]`;
 };

var escapeRegExp = s => makeString(s).replace(/([.*+?^=!:${}()|[\]\/\\])/g, '\\$1');
```

**Comment by sergeyt** [comment]
@eventualbuddha JS version looks good.

**Comment by ramya-rao-a** [comment]
https://github.com/jonjonsonjr/diff-parse claims to be the javascript version. Thoughts?

**Comment by sergeyt** [comment]
done by @alikhamesy
