### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by armenzg** [sergeyt/parse-diff#20]
This HG diff is causing parse-diff to fail:
https://hg.mozilla.org/mozilla-central/rev/4e655361be5a
https://hg.mozilla.org/mozilla-central/raw-rev/4e655361be5a

The description is extremely long and has lots of characters that could cause it.

**Comment by armenzg** [comment]
Thanks for the project!

**Comment by sergeyt** [comment]
@armenzg PR #21 fixes this issue very stupidly. I am considering changing interface of `parseDiff` function to return object with `synopsis` and changed `files` fields. A patch could optionally start with `synonpsis`. Please share your thoughts.

**Comment by armenzg** [comment]
👍 

hi @sergeyt don't worry about it! I make mistakes like that too.

Either approach works for me. As long as I can still acess the metadata and the different files and lines involved in a patch I'm happy :)

**Comment by sergeyt** [comment]
@armenzg ok lets merge this fix, and later if needed consider supporting synopsis field

**Comment by sergeyt** [comment]
fixed in parse-diff@0.4.2

**Comment by armenzg** [comment]
I've deployed the latest package and it is working!!
Thank you very much @sergeyt !!
