### ISSUE TITLE
Any way to convert back the parsed object into diff string ?

### ISSUE THREAD

**Issue by melkishengue** [sergeyt/parse-diff#29]
My use case is that after parsing the diff string, I perform some modifications on the object, and I would like to save it back as a diff string for further processing. is this possible using this library ? Thanks

**Comment by sergeyt** [comment]
Nope, you have to implement this in your app. What kind of modifications? It seems ignoring a chunk is pretty easy to do to me.

**Comment by melkishengue** [comment]
My goal is to ignore some del/add chunks based on some string patterns, so I guess making them of type normal would pretty much do it. But I need to have the whole object back as diff string after processing. Could you please provide with some examples how you would achieve ignoring chunks ? thanks in advance.

**Comment by sergeyt** [comment]
sure here is a snippet to generate an idea:

```javascript
const files = parse(diff);
const newDiff = files.map(f => 
   f.chunks
    // filter out del chunks
    .filter(c => c.type != "del")
    // concat all changes
    .map(c => c.changes.map(t => t.line).join("\n")).join("\n"))
);
```
